### ISSUE TITLE
About mini-batch in your model

### ISSUE THREAD

**Issue by ChunchaoPeter** [kasparmartens/c-GPLVM#1]
Hi Kaspar,

I am currently reading your code. I am new to PyTorch and Computer.  I am really like your work.

When I am reading the PyTorch online, I find that " torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample. "

When I reading your code, I find that your model inherited from the nn.Module. 

class GPLVM(nn.Module):

Could you please tell me how can you address the mini-batches problem ?

Thanks in advance.

Best wishes,
Chunchao

**Comment by kasparmartens** [comment]
Hi, 

Our current c-GPLVM implementation does not support minibatching. It implements the ELBO from [Titsias 2009] (the same bound that e.g. has been implemented here https://github.com/GPflow/GPflow/blob/develop/gpflow/models/sgpr.py#L86), with the difference that instead of fixed inputs x we use a combination of latent variables z (which are sampled via reparameterisation) and fixed inputs x.

**Comment by ChunchaoPeter** [comment]
Hi Kaspar,


Thanks for your response. I think I have not explain my question clearly. Sorry about that.

I would like to avoid the mini-batch but use the whole training dataset in PyTorch. However, when I am reading the PyTorch online, I find that " torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample. " If I am correct, I am not allowed to use the whole dataset to implement the GP or optimize GP. For example, in the optimization part, we only use mini-batch data to optimize our model. 

When I reading your code, I find that your model inherited from the nn.Module.
class GPLVM(nn.Module): 
(You have not implement the mini-batch part)

It seems to that it is contradiction to "torch.nn only supports mini-batches. ", if I am correct.

I think I could misunderstand some part. 

Is it possible for you to tell me what is " torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample. "? 

Can the mini-batch be used as the whole data in our Gaussian process model ?  

Thanks again.


Best wishes,
Chunchao

**Comment by kasparmartens** [comment]
> "torch.nn only supports mini-batches. "

There is nothing in PyTorch (or TensorFlow) which stops you from passing the entire data set through the model (e.g. neural network). From an implementation perspective, "full data" is a special case of minibatch. 

In our case, we simply use PyTorch as a means to code up the GP matrix algebra (in principle, the PyTorch functionality would let us pass a subset of the data through the GPLVM, but we have to keep in mind that this is not a correct thing to do).

**Comment by ChunchaoPeter** [comment]
Hi Kaspar,

Great! Thanks for your help. :)
Thanks again.


Best wishes,
Chunchao
